# Generated by Django 5.2.2 on 2025-06-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_title_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="uploaded_by",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
