# Generated by Django 5.2.2 on 2025-06-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_uploaded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="id_hash",
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
