# Generated by Django 5.2.2 on 2025-06-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_document_id_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="id_hash",
        ),
    ]
