# Generated by Django 5.2.2 on 2025-06-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_remove_document_id_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="raw_bytes",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
