# Generated by Django 5.2.2 on 2025-06-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_document_raw_bytes"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="size",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
