# Generated by Django 5.2.2 on 2025-06-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_documentimages"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="documentimages",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="documentimages",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentimages",
            name="extracted_at",
        ),
        migrations.RemoveField(
            model_name="documentimages",
            name="page_number",
        ),
    ]
