# Generated by Django 5.2.2 on 2025-06-10 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_alter_documentimages_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("page_number", models.PositiveIntegerField()),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DocumentImages",
        ),
    ]
