# Generated by Django 5.2.2 on 2025-06-13 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_entity"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("toc", models.JSONField(blank=True, null=True)),
                ("full_text", models.TextField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("reading_time", models.PositiveIntegerField(default=0)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("words_count", models.PositiveIntegerField(default=0)),
                ("images_extracted_count", models.PositiveIntegerField(default=0)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
            ],
        ),
    ]
