# Generated by Django 5.2.2 on 2025-06-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_documentanalytics"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="original_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
