# Generated by Django 5.2.2 on 2025-06-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0013_document_original_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentimage",
            name="image",
            field=models.BinaryField(),
        ),
    ]
